"""
Requirement extraction from a job description.

Previous behaviour (fixed here): a single-paragraph JD produced one "requirement"
that was the entire 300-character paragraph echoed back, followed by seven
"Experience with <keyword>" stubs generated by substring-matching a hardcoded tech
list. The paragraph-length requirement then matched every candidate weakly, which
compressed the whole ranking toward the mean.

The extractor now segments before it filters. Requirements live inside clauses, not
inside paragraphs, so the JD is split on sentence and list-separator boundaries first
and every candidate is length-bounded. Keyword expansion still exists, but only as a
rescue path when segmentation genuinely found too little — it no longer pads a result
that was already good.
"""
from __future__ import annotations

import re
from collections.abc import Iterable

from app.models.schemas import Requirement

# Minimum number of segmented requirements before keyword expansion is allowed to help.
_EXPANSION_FLOOR = 3
_MAX_REQUIREMENT_CHARS = 140
_MIN_REQUIREMENT_CHARS = 12

_TECH_KEYWORDS = [
    "python", "fastapi", "rag", "retrieval", "vector database", "embeddings", "llm",
    "machine learning", "nlp", "docker", "kubernetes", "aws", "gcp", "azure", "streamlit",
    "sql", "evaluation", "prompt engineering", "langchain", "langgraph", "faiss", "pytorch",
    "tensorflow", "fine-tuning", "agents", "distributed systems", "microservices",
]
_ACRONYMS = {"ai", "ml", "nlp", "rag", "llm", "llms", "sql", "aws", "gcp", "api", "apis"}

# A clause is a requirement if it makes a demand or names a capability.
_REQUIREMENT_SIGNAL = re.compile(
    r"\b(must|should|required|require|experience|proficien\w*|knowledge|familiar\w*|expertise|"
    r"strong|demonstrated|ability|build\w*|design\w*|develop\w*|deploy\w*|maintain\w*|own\w*|"
    r"ship\w*|years?|degree|bachelor|master|phd|python|java|ml|ai|rag|fastapi|docker|sql|"
    r"aws|gcp|azure|kubernetes|pytorch|langchain|langgraph)\b",
    re.IGNORECASE,
)
_MUST_HAVE_SIGNAL = re.compile(
    r"\b(must|must[- ]have|required|require[sd]?|mandatory|essential|minimum|at least|\d+\+? years?)\b",
    re.IGNORECASE,
)
_NICE_TO_HAVE = re.compile(r"\b(nice to have|bonus|plus|preferred|desirable|a plus)\b", re.IGNORECASE)

# Section headings and boilerplate that are never requirements.
_BOILERPLATE = re.compile(
    r"^(responsibilities|requirements|qualifications|about (us|the role|the team)|who you are|"
    r"what you.ll do|we are (hiring|looking)|benefits|compensation|equal opportunity|apply)\b",
    re.IGNORECASE,
)

_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")
# Clause separators that survive inside a single sentence: semicolons, bullets, and
# the ", and " / ", or " joins that JDs use to stack three demands into one line.
_CLAUSE_SPLIT = re.compile(r"\s*(?:;|•|·|•|‣|\|)\s*|,\s+(?:and|or)\s+")


class RequirementExtractor:
    def __init__(self, *, chat_model: str = "local-rule-based", openai_api_key: str = "", max_requirements: int = 8) -> None:
        self._max_requirements = max_requirements

    def extract(self, title: str, description: str) -> list[Requirement]:
        segments = self._segment(description)
        scored = [item for item in self._select(segments) if not self._is_title_echo(item[0], title)]

        if len(scored) < _EXPANSION_FLOOR:
            for skill in self._extract_skill_phrases(description):
                scored.append((f"Experience with {skill}", 1.0, False))

        unique = list(self._unique(scored))[: self._max_requirements]
        return [
            Requirement(
                id=f"req_{index}",
                text=text,
                weight=max(0.5, min(weight, 2.0)),
                must_have=must_have,
            )
            for index, (text, weight, must_have) in enumerate(unique, start=1)
        ]

    @staticmethod
    def _is_title_echo(text: str, title: str) -> bool:
        """Drop the JD's own headline.

        "AI Engineer, Talent Platform" contains 'AI', which is enough to look like a
        requirement to any keyword filter. It is the title of the posting, not something
        a candidate can provide evidence for, and as a requirement it matches everyone
        weakly and compresses the ranking.
        """
        def normalise(value: str) -> list[str]:
            return re.sub(r"[^a-z0-9 ]", " ", value.lower()).split()

        text_tokens, title_tokens = normalise(text), normalise(title)
        if not title_tokens or len(text_tokens) > len(title_tokens) + 3:
            return False
        overlap = len(set(text_tokens) & set(title_tokens))
        return overlap >= max(1, len(title_tokens) - 1)

    # -- segmentation ------------------------------------------------------

    def _segment(self, description: str) -> list[str]:
        """Line -> sentence -> clause. Requirements live at clause level, not paragraph level."""
        segments: list[str] = []
        for line in description.splitlines():
            line = line.strip(" -•·\t*")
            if not line:
                continue
            for sentence in _SENTENCE_SPLIT.split(line):
                sentence = sentence.strip()
                if not sentence:
                    continue
                pieces = [piece.strip(" -•·,") for piece in _CLAUSE_SPLIT.split(sentence)]
                # Splitting is only worth it if it actually produced usable clauses;
                # otherwise a comma-free sentence would be discarded for being long.
                usable = [p for p in pieces if len(p) >= _MIN_REQUIREMENT_CHARS]
                segments.extend(usable if len(usable) > 1 else [sentence])
        return segments

    def _select(self, segments: Iterable[str]) -> list[tuple[str, float, bool]]:
        selected: list[tuple[str, float, bool]] = []
        for segment in segments:
            text = self._clean(segment)
            if not (_MIN_REQUIREMENT_CHARS <= len(text) <= _MAX_REQUIREMENT_CHARS):
                continue
            if _BOILERPLATE.match(text):
                continue
            if not _REQUIREMENT_SIGNAL.search(text):
                continue
            must_have = bool(_MUST_HAVE_SIGNAL.search(text)) and not _NICE_TO_HAVE.search(text)
            if _NICE_TO_HAVE.search(text):
                weight = 0.6
            elif must_have:
                weight = 1.4
            else:
                weight = 1.0
            selected.append((text, weight, must_have))
        # Must-haves first, then by weight, so a max_requirements cut never drops a hard filter.
        selected.sort(key=lambda item: (not item[2], -item[1]))
        return selected

    def _extract_skill_phrases(self, description: str) -> list[str]:
        lowered = description.lower()
        found: list[str] = []
        for keyword in _TECH_KEYWORDS:
            if re.search(rf"\b{re.escape(keyword)}\b", lowered):
                found.append(keyword.upper() if keyword in _ACRONYMS else keyword)
        return found

    def _clean(self, text: str) -> str:
        text = re.sub(r"\s+", " ", text).strip().rstrip(".,;")
        text = re.sub(
            r"^(responsibilities|requirements|qualifications|you will|we need|must have)\s*[:\-]\s*",
            "",
            text,
            flags=re.IGNORECASE,
        )
        return text.strip()

    def _unique(self, items: Iterable[tuple[str, float, bool]]) -> Iterable[tuple[str, float, bool]]:
        seen: set[str] = set()
        for text, weight, must_have in items:
            key = re.sub(r"[^a-z0-9 ]", "", text.lower()).strip()
            if key in seen:
                continue
            seen.add(key)
            yield text, weight, must_have
